keep-going: True
rerun-incomplete: True
printshellcmds: True
notemp: True
cleanup-containers: True
conda-cleanup-pkgs: cache
software-deployment-method: conda apptainer
apptainer-args: "--bind {{cookiecutter.apptainer_args}}"

